# Site settings
title: "xD - U.S. Census Bureau"
description:
  "xD is an emerging technologies group that’s advancing the delivery of
  data-driven services through new and transformative technologies."
baseurl: ""
permalink: pretty
localhost: "localhost:4500"
env: "production"
logo: /assets/img/logos/18F-Logo-Bright-S.png
tag_dir: tags
github_repo: https://github.com/XDgov/xd.gov/blob/master

related_posts: 3

analytics:
  google:
    code: "UA-123456-1" # Change this to your GSA analytics code
  dap:
    agency: Commerce # Change this to your agency
    subagency: Census # Change this to your agency

collections_dir: collections
collections:
  news:
    output: true
    permalink: /news/:permalink/
  positions:
    output: true
  projects:
    output: true
    permalink: /projects/:permalink/
  blog:
    output: true
    permalink: /blog/:permalink/
  import:
    output: true
  team_members:
    output: true

defaults:
  - scope:
      type: "posts" # an empty string here means all files in the project
    values:
      layout: post
  - scope:
      path: "pages"
    values:
      layout: default
  - scope:
      path: "_projects"
    values:
      layout: project
  - scope:
      path: "_news"
    values:
      layout: news
  - scope:
      path: "_blog"
    values:
      layout: blog
  - scope:
      path: "_team_members"
    values:
      layout: team-member

# Build and syntax highlighting settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: "syntax"

# Settings for HTML compression: https://www.digitalocean.com/community/tutorials/jekyll-compress-html
compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

exclude:
  - .about.yml
  - .cfignore
  - .codeclimate.yml
  - .gitignore
  - .gitmodules
  - .hound.yml
  - 404.html
  - api-endpoints
  - bin
  - build
  - circle.yml
  - config_blog.rb
  - CONTRIBUTING.md
  - docker-compose.yml
  - docker_entrypoint.rb
  - Dockerfile
  - examples/
  - favicon.ico
  - Gemfile*
  - ISSUE_TEMPLATE.md
  - killport
  - LICENSE.md
  - node_modules
  - package.json
  - pages/our-work.html
  - PULL_REQUEST_TEMPLATE.md
  - README.md
  - spec/
  - system-security-plan.yml
  - tests/
  - tests/schema/tags.yml
  - tmp/
  - vendor

include:
  - _pages

# jekyll plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: assets/css/
