# Site settings
title: "xD is a government product studio. | xd.gov"
description: "xD builds ...."
baseurl: "https://cg-843bb463-d0c8-4a3a-9aaf-c477e7d4a901.app.cloud.gov/site/loganpowell/xd.gov" # the subpath of your site, e.g. /blog
permalink: pretty
url: "https://cg-843bb463-d0c8-4a3a-9aaf-c477e7d4a901.app.cloud.gov" # the base hostname & protocol for your sites
localhost: "localhost:4500"
env: "production"
logo: /assets/img/logos/18F-Logo-Bright-S.png
tag_dir: tags
github_repo: https://github.com/XDgov/xd.gov/blob/master

related_posts: 3


analytics:
  google:
    code: 'UA-123456-1' # Change this to your GSA analytics code
  dap:
    agency: Commerce    # Change this to your agency
    subagency: Census # Change this to your agency

collections:
  news:
    output: true
    permalink: /news/:permalink/
  positions:
    output: false
  projects:
    output: true
    permalink: /projects/:permalink/

defaults:
 -
  scope:
    type: "posts" # an empty string here means all files in the project
  values:
    layout: post
 -
  scope:
    path: "pages"
  values:
    layout: default
 -
  scope:
    path: "_projects"
  values:
    layout: project
 -
  scope:
    path: "_news"
  values:
    layout: news

# Build settings
markdown: kramdown
highlighter: rouge

exclude:
- .about.yml
- .cfignore
- .codeclimate.yml
- .gitignore
- .gitmodules
- .hound.yml
- 404.html
- api-endpoints
- bin
- build
- circle.yml
- config_blog.rb
- CONTRIBUTING.md
- docker-compose.yml
- docker_entrypoint.rb
- Dockerfile
- examples/
- favicon.ico
- Gemfile*
- ISSUE_TEMPLATE.md
- killport
- LICENSE.md
- node_modules
- package.json
- pages/our-work.html
- PULL_REQUEST_TEMPLATE.md
- README.md
- spec/
- system-security-plan.yml
- tests/
- tests/schema/tags.yml
- tmp/
- vendor

include:
  - _pages

# jekyll plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: assets/css/
